= Audiobook Creator - Readme  
@Date : 8.5.2024  
@Category : Readme  

== What is Audiobook Creator?  

* This project creates audiobooks from plain text files.  
* It uses the Python TTS and xTTS models to synthesize natural human-sounding audio.  
* Powered by TTS and XTTS 

== Requirements :  

.Requirements :  
* python3.10-pip  
* python3-virtualenv  

== Installation :  

.Installation :  
* Just run the following to install the Python modules  
* $ ./install_requirements.sh  

== Usage :  

Usage :

.Usage :
* Just run the following to create an audiobook containing several audio - wav files.
* $ ./create_audiobook.sh <PATH_TO_YOUR_TEXT> <AUDIOBOOK_NAME> 
* It will create a folder with your AUDIO_BOOK_NAME, create audio files from your text, and place them into this folder.
* Please note that you will need a CUDA-capable GPU in order to run the voices as they work with deep neural networks in order to provide high-quality TTS.

== Supported Languages : 

.Currently we support : 
* German 
* English 

* We will add more languages in later releases. 
* We need to download a spacy model for each language in order to split the book to sentences correctly. 

=== Create Speaker - Samples : 

* You can now select the speaker for your Audio-Book within a dropdown on the top of the Web_Server. 
* You can create a sample wav-file for each supported speaker as follows. 
* $ source audiobook_venv/bin/activate && \
* $ cd create_voice_samples && \
* $ python ./CreateVoiceSamples.py 
* They will be created into subdirectories of the name of the speaker they applay to. 
* You can just copy this wav-files into a custom folder under the Web_Server - Directory to be able to brows them from the frontend. 

== Webserver : 
=== Attension ! Do only use it inside secure local or vpn - networks ! It is not ready to be used as service online !  

* The web-server can be used to work with audiobook-creation from another device like a smartphone. 
* It should only be used within secure networks as it dows not implement any security or privacy functionality. 
* Please note that currently the complete folder structure is shown to the user. This will e fixed in later versions. For the moment you should only use it within your vpn or local network!!! 

=== Usage : 

* $ source audiobook_venv/bin/activate && cd Web_Server && python ./AudiobookCreatorWebServer.py 
* It will runn under localhost:5000 
* You can insert your text into the textfeald or upload a .txt file. 
* The created audiobooks will show up as folders in the directory Tree. 
* You can play them by klicking on the dirctory and after then just on play. 

=== Translation : 

* You can translate texts from english to german and wise versa. 
* Just use the toggle-button on the web-frontend. 
* Please keep attension of the outputs as they are currently produced via llama3.
** Large Language Models can make mistakes. 
** Always check importent information. 
* Please note also that translating is not yet supported to be run on the same gpu that the tts is working on. Especialy if your vram is not larger then 24 GB. 
** Just try it out, there may bee memory-problems. 

