= Todo : Bugfixes and Feature-requests : 
@Author : Joshua Jama 
@Date : 29.6.2024 
@Category : Todo, bugg-fixes, feature-requests 




== Bugg-Fixes: 

* Chunklänge für sehr lange auflistung überprüfen wird anscheinend manchmal zu lang gelassen 
** Wird im Momment mit zwei verschachtelten Exceptions abgefangen. Innerhalb der innersten Ebene wird fals der Chunk immer noch zu lang für die 400 - token - Grenze von xtts ist eine Fehlermeldung im Resultierenden Audio gesprochen. 
* Die license von cockwi tts akzeptieren im browser möglich machen durch den pflask server 
* Pyenv  für die installation der version 3.10 benutzen bevor der installer ausgeführt wird 
* Normalisierung der wav 
* Regex for copyright 

== Feature-Requests : 


* Text  im player anzeigen  dafür chunks  auf speichern 
** Im Momment kann die Textstelle in der audio_files_log.txt log - Datei nachvollzogen werden. Diese ist im jeweiligen Audiobook-Order abruhfbar. 
* Log in browser 
* Falsche Datein im Browser verstecken 
* Alle von xtts unterstützten Sprachen bei den spacy model download im installer einfügen. 
* Installation of ollama-server within the requirements-install. 


== Solved : 

=== XTTS can only process texts to a size of 400 tokens problem : 

* When text-file greater then 10000 chars : the followin error is shown : xtts can only process 400 token 
* That may also be caused by copyright caractors or to long sentences. 

=== Bugg-Fixes : 
* Exception für maximum token anzahl für text und spacy oder xtts ueberschritten. 

=== Feature-Requests : 

* Auswahlfeld fuer die Stimme
* Translation
* Just works with the first chunk until now as if we need to make new chunks after translating as if the sentences do not automaticaly fit the limits. 
* I get a memory-error for my vram, but did not reach to find the cause of this problem. 
** We need to seperate the translation from the tts-creation. 
** It may also be required to delete the ollama-model from the vram of the gpu manualy. 

