from CreateAudiobook import * 

# Te speaker idxs to select for xtts : 
speaker_idxs = [
'Claribel Dervla', 
'Daisy Studious', 
'Gracie Wise', 
'Tammie Ema', 
'Alison Dietlinde', 
'Ana Florence', 
'Annmarie Nele', 
'Asya Anara', 
'Brenda Stern', 
'Gitta Nikolina', 
'Henriette Usha', 
'Sofia Hellen', 
'Tammy Grit', 
'Tanja Adelina', 
'Vjollca Johnnie', 
'Andrew Chipper', 
'Badr Odhiambo', 
'Dionisio Schuyler', 
'Royston Min', 
'Viktor Eka', 
'Abrahan Mack', 
'Adde Michal', 
'Baldur Sanjin', 
'Craig Gutsy', 
'Damien Black', 
'Gilberto Mathias', 
'Ilkin Urbano', 
'Kazuhiko Atallah', 
'Ludvig Milivoj', 
'Suad Qasim', 
'Torcull Diarmuid', 
'Viktor Menelaos', 
'Zacharie Aimilios', 
'Nova Hogarth', 
'Maja Ruoho', 
'Uta Obando', 
'Lidiya Szekeres', 
'Chandra MacFarland', 
'Szofi Granger', 
'Camilla Holmström', 
'Lilya Stainthorpe', 
'Zofija Kendrick', 
'Narelle Moon', 
'Barbora MacLean', 
'Alexandra Hisakawa', 
'Alma María', 
'Rosemary Okafor', 
'Ige Behringer', 
'Filip Traverse', 
'Damjan Chapman', 
'Wulf Carlevaro', 
'Aaron Dreschner', 
'Kumar Dahl', 
'Eugenio Mataracı', 
'Ferran Simen', 
'Xavier Hayasaka', 
'Luis Moray', 
'Marcos Rudaski'
]
def create_voice_samples(): 
  for speaker_idx in speaker_idxs : 
    output_path = speaker_idx 
    output_path = output_path.replace(" ", "-") 
    create_audio_tts("./snipet.txt", "de", output_path, speaker_idx)

create_voice_samples() 
